Update OrangeFox-Compile.yml
Signed-off-by: Shahed420 <57837102+Shahed420@users.noreply.github.com>

diff --git a/.github/workflows/OrangeFox-Compile.yml b/.github/workflows/OrangeFox-Compile.yml
--- a/.github/workflows/OrangeFox-Compile.yml
+++ b/.github/workflows/OrangeFox-Compile.yml
@@ -41,21 +41,32 @@ jobs:
         curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
         chmod a+x ~/bin/repo
         sudo ln -sf ~/bin/repo /usr/bin/repo
-
     
+    - name: Sync Manifest
+      run: |
+        mkdir -p ${GITHUB_WORKSPACE}/PBRP
+        cd ${GITHUB_WORKSPACE}/PBRP
+        git config --global user.name "${{ github.actor }}"
+        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
+        repo init --depth=1 -u https://github.com/PitchBlackRecoveryProject/manifest_pb.git -b android-12.1
+        repo sync -j$(nproc --all) --force-sync --no-tags --no-clone-bundle --prune --optimized-fetch
+
     - name: Clone Device Tree
       run: |
-        cd ${GITHUB_WORKSPACE}
-        mkdir -p PBRP
-        cd PBRP
-        git clone ${{ inputs.DEVICE_TREE }} -b main ${{ inputs.DEVICE_PATH }}
+        cd ${GITHUB_WORKSPACE}/PBRP
+        git clone --depth=1 ${{ inputs.DEVICE_TREE }} -b main ${{ inputs.DEVICE_PATH }}
 
     - name: Building PBRP
       run: |
         cd ${GITHUB_WORKSPACE}/PBRP
+        if [ ! -f "build/envsetup.sh" ]; then
+          echo "ERROR: Source code not downloaded correctly!"
+          ls -a
+          exit 1
+        fi
         source build/envsetup.sh
         export ALLOW_MISSING_DEPENDENCIES=true
-        lunch twrp_X6725B-eng
+        lunch twrp_${{ inputs.DEVICE_NAME }}-eng
         make clean
         mka pbrp -j$(nproc --all)
 
